// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtgfbqxwapmwjqkmseru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Z2ZicXh3YXBtd2pxa21zZXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTczNzgsImV4cCI6MjA2ODQzMzM3OH0.F31-2oweMXPMX9amKU1_6meWN-jcR8ui-p_LL-C9OII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});